Sync name.dets to disk
rabbitmq/ra pull request #443
Opened 2024-05-18 12:34 UTC by visciang

## Proposed Changes

I have seen `names.dets` being left not in sync with the system state (server directory name).

The operations that trigger the problem are:

1. start the app
2. create a raft server X (UID-123)
3. leave_and_delete the server X
4. re create the raft server X (UID-456)
5. immediately stop the app (<<<=== before the DETS auto_sync the new registered name of the disk - 500ms)

So, in other words, we are "resetting" an existing ra server (3+4).

What I've seen is that `names.dets` refer to the ra server identifier created at step 2 - UID-123 (the first instance of the server X).
When I restart the application, ra crashes while strarting with error `enoent` since the ra server directory UID-123 does not exist anymore (deleted by step 3).

Here a view of what I see - `names.dets` refer to  the server "ELIXIRXR9LYKF78Z3R" (it's the one created on step 2) while on disk I see the server "ELIXIRHP06E8L3EYLT" (created on step 4).

<img width="778" alt="image" src="https://github.com/rabbitmq/ra/assets/15736959/b36c37b1-78ea-4cbf-a2b0-2bd79d07c6de">

I've been able to "fix" the problem introducing a `dets:sync` call after each change operation in `ra_directory` module, following what is already in place in the `ra_log_metadata` module.

@kjnilsson I have not jet created an ISSUE to link to this PR, would like to get a feedback from you first.
Even if the change is small, and I think should not break existing stuff and lower down the performance, maybe there is a better architectural approach you can come to - since given the non atomicity of writing to a dets can always lead to a dets that has not been updated (ie erlang app killed after a `dets:insert` but before the `dets:sync`).
Let me know if you need more information.

## Types of Changes

- [X] Bug fix (non-breaking change which fixes issue "NOT JET OPENED")
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [X] I have read the `CONTRIBUTING.md` document
- [X] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [X] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

2024-05-18 12:34 UTC, pivotal-cla commented
@visciang Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/ra&pullRequestId=443)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/ra&pullRequestId=443) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2024-05-18 12:36 UTC, pivotal-cla commented
@visciang Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/ra&pullRequestId=443)!

2024-05-19 04:01 UTC, michaelklishin commented
@visciang it's fine not to file an issue first if you explain the reasoning behind the change and various design considerations (if any) in the PR. I think we have enough information here. 

Thank you for taking the time to contribute!

2024-05-19 04:06 UTC, michaelklishin commented
FTR, the functions affected should not be used on the hot code path, so this PR is very unlikely to introduce a throughput hit with reasonable workloads:

 * `ra_directory:deinit/1`
 * `ra_directory:register_name/6`
 * `ra_directory:unregister_name/2`

2024-05-19 04:06 UTC, michaelklishin approved these changes

2024-05-19 06:27 UTC, kjnilsson commented
This is likely to affect definition import performance in RabbitMQ.

*Karl Nilsson*


On Sun, 19 May 2024 at 05:06, Michael Klishin ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rabbitmq/ra/pull/443#pullrequestreview-2064987335>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJAHFD7AWX7ACNZT4VL3KTZDAQODAVCNFSM6AAAAABH5N2BM2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANRUHE4DOMZTGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-20 08:47 UTC, kjnilsson requested changes
I think it should be sufficient to retain the change in `ra_directory:deinit/1` and remove the other calls to `dets:sync/1` as they are likely to have a negative performance impact on RabbitMQ.

2024-05-20 08:47 UTC, kjnilsson commented on src/ra_directory.erl
> +            ok = dets:sync(DirRev);
I think this can have negative performance impact in RabbitMQ

2024-05-20 08:47 UTC, kjnilsson commented on src/ra_directory.erl
> +            ok = dets:sync(DirRev),
This can also affect RabbitMQ performance negatively.

2024-05-20 09:50 UTC, kjnilsson approved these changes

2024-05-20 09:51 UTC, merged

2024-05-20 09:51 UTC, kjnilsson commented
Cheers