Delay machine upgrade until all members are up-to-date
rabbitmq/ra pull request #493
Opened 2024-12-24 12:21 UTC by dumbbell

[TBW]

2025-01-02 09:35 UTC, kjnilsson requested changes
looks good, a few tweaks and a question as to whether we should optionally keep the old behaviour or not.

2025-01-02 09:35 UTC, kjnilsson commented on src/ra.hrl
> +         info :: ra_server:ra_server_info() | undefined}).
default this to `#{}` and remove the `undefined` option?

2025-01-02 09:35 UTC, kjnilsson commented on src/ra_server.erl
> +info_reply_effect(
this should fit to the right of `(` so no need for newline here.

2025-01-02 09:35 UTC, kjnilsson commented on src/ra_server.erl
> +            %% We continue to send the `noop' command immediately after
I am wondering if we should build in a mechanism to keep the old behaviour

2025-01-02 09:35 UTC, kjnilsson commented on src/ra_server.erl
> +                         %% The peer is in a Raft state where it can't give
I think a peer should always be able to provide info for keys it understands.

2025-01-02 09:35 UTC, kjnilsson commented on src/ra_server.erl
> +    Effects = case has_enough_peer_info(State) of
do we need `has_enough_peer_info` at all if the later `get_max_supported_machine_version` could handle the case where some peers do not yet have a common machine version?

2025-01-06 09:17 UTC, dumbbell commented on src/ra_server.erl
> +            %% We continue to send the `noop' command immediately after
Like an option in the Ra server config to perform the machine upgrade as soon as a leader with the new version is elected as before?

2025-01-06 09:18 UTC, dumbbell commented on src/ra_server.erl
> +                         %% The peer is in a Raft state where it can't give
Ok, so I should get rid of the `empty_info_reply_effect()` function and let a Ra server always send its machine version in the `#info_reply{}`, correct?

2025-01-06 09:59 UTC, kjnilsson commented on src/ra_server.erl
> +            %% We continue to send the `noop' command immediately after
yes - just in case someone isn't ready to change to the new behaviour yet or we want to switch back for QQ for example. I'm thinking we could make it a ra system config key rather than a server config key.

2025-01-06 09:59 UTC, kjnilsson commented on src/ra_server.erl
> +                         %% The peer is in a Raft state where it can't give
yes I think that makes sense,

2025-01-06 10:31 UTC, dumbbell commented on src/ra_server.erl
> +                         %% The peer is in a Raft state where it can't give
In fact, disregard that previous comment.

2025-01-06 10:33 UTC, dumbbell commented on src/ra.hrl
> +         info :: ra_server:ra_server_info() | undefined}).
Done

2025-01-06 10:33 UTC, dumbbell commented on src/ra_server.erl
> +info_reply_effect(
Done

2025-01-06 10:34 UTC, dumbbell commented on src/ra_server.erl
> +                         %% The peer is in a Raft state where it can't give
Addressed too :)

2025-01-06 10:34 UTC, dumbbell commented on src/ra_server.erl
> +    Effects = case has_enough_peer_info(State) of
I merged the two functions.

2025-01-07 09:18 UTC, dumbbell commented on src/ra_server.erl
> +            %% We continue to send the `noop' command immediately after
Thank, let me change that! Any preferences for the name? I’m not satisfied with the `machine_upgrade_when` I came up with.

2025-01-07 10:20 UTC, dumbbell commented on src/ra_server.erl
> +            %% We continue to send the `noop' command immediately after
So I moved the option from the server to the system. The name is still `upgrade_machine_when` with two possible values: `after_election` or `when_available_everywhere`, the latter being the default.

That default is set in `src/ra_server.hrl`. `ra_system` queries the application environment and falls back to the default as part of the default system configuration.

2025-01-09 09:27 UTC, kjnilsson commented on src/ra_server.erl
> +-type upgrade_machine_when() :: after_election | when_available_everywhere.
we could consider `-type machine_upgrade_strategy() :: all | quorum.`

2025-01-09 10:14 UTC, dumbbell commented on src/ra_server.erl
> +-type upgrade_machine_when() :: after_election | when_available_everywhere.
Suggestion applied :)

2025-01-09 10:21 UTC, kjnilsson approved these changes

2025-01-09 10:30 UTC, merged